### ISSUE TITLE
Voyager apps: add warning if missing rom file option

### ISSUE THREAD

**Issue by macmpi** [mike632t/x11-calc#11]
>No ROM images are included for the HP10C, HP11C, HP12C, HP15C, and HP16C.

It would be helpful to warn user at launch if no file is supplied/nor in correct format.

**Comment by mike632t** [comment]
Although when launching the application from a modern desktop the user won't see any messages on stdout that does seem like a good idea, particularly if like me you launch an application from the command line just to see if it does print anything when it doesn't work.  I probably should also add a message to confirm the ROM file being used 

Of course what I'd like to do would be to print the message 'no rom' on the display but I can't do that as only having 7 segments limits the characters you can use and I cant think of a way to get something meaningful out of the letters available, that is different enough not to be confused that a real error message so I'm not so keen on that... 

I did think that I could try writing some new code to put into the default ROM that did something with the display that was totally unique like displaying a spinner in each digit position, but even if that was possible (and it probably is) the down side is that it would destroy the contents of the registers which would not be a good thing as the chances are that the next time the simulator was started it would crash as the voyager series rely on the system state being maintained all the time.

BTW - I assume you have a ROM for the voyager machines?  If you don't search github for nonpariel 0.77 (the voyager ROMs were removed from nonpariel 0.78, which is why I don't include them), but they were already available in the older versions.  However, they are slightly modified as you will probably quickly notice when you run a program!

**Comment by macmpi** [comment]
I think console hint is good enough for debugging.
For example: `x11-calc-11c` with no -r option never complains, while it won't work properly: it should probably issue a warning.
`x11-calc-11c` with  -r option pointing to non-existing file does issue proper warning: fine.

>BTW - I assume you have a ROM for the voyager machines?

Recent nonpareil master brought Voyager [roms](https://github.com/brouhaha/nonpareil/tree/main/ncd/) back.
In my tentative flatpak I did add a [launcher shell script](https://github.com/macmpi/x11-calc-flatpak/blob/main/x11-calc-launcher.sh) which selects calculator model and sets default -r option for Voyager models (unless an option is already set in some conf file): with -r option filled, warning will be issued if file is indeed missing.
Initially launcher was also pulling Voyager rom file from nonpareil repo if not already provided, but I removed that part as I was unsure about licensing conditions for such files.

**Comment by mike632t** [comment]
I didn't wan't to add another flag and after thinking about the problem for a bit I decided to implement a more generic test to check to see if the ROM contents were empty, that way if the the ROM isn't defined by default in the emulator, or if the user specifies a ROM file and the contents are are not readable (empty file, or no data) the error will be caught.  

This solution does depend on the compiler initialising the contents of the ROM to zeros if it isn't defined, and won't catch a single invalid line in a ROM file, so it has its faults... 

I have committed my changes to the unstable branch for now.
