### ISSUE TITLE
Add 320x200 and 320x240 skin

### ISSUE THREAD

**Issue by u2fly** [mike632t/x11-calc#116]
Add `320x200` (for VGA display, Atari, Amiga, etc.) and `320x240` screen resolutions for 10C/11C/12C/15C/16C.

Here is 320x200 mockup for 15C: 
![x11-calc-15c-320x200](https://github.com/user-attachments/assets/28fc01d5-dfb1-4c44-8844-2fd5d72211fd)

Nokia E-series mockup (system top and bottom bars occupies 40px in height on 320x240 display):

<img src="https://github.com/user-attachments/assets/3a03b8b2-ba0b-4d1f-ac7d-05b4f8b090b9" width="320"/>

**Comment by mike632t** [comment]
Sorry I didn't see this earlier.  

If you want to use a VGA display the window size isn't the only problem as VGA only supports 256 colours and the application currently requires 24-bit colour.

When I figure out how to resize fonts I'd like to be able to allow the window size to be set from the command line using something like `--geometry=WidthxHeight+Xposition+Yposition` but right now that isn't possible (I would have to replace the current font based characters with a solution based on re-sizeable bitmaps and that would be a _lot_ of work).

However, you can get close to the result you want by modifying the source code

First modify `x11-calc.h` to change the SCALE_WIDTH and SCALE_HEIGHT (you may need to mess around with the values a bit to get exactly the size you want).

```
#if !defined(SCALE_WIDTH)
#define SCALE_WIDTH     0.76
#endif
#if !defined(SCALE_HEIGHT)
#define SCALE_HEIGHT    0.76
#endif
```
This works (sort of), but the resulting display isn't pretty... 

You can improve this by modifying  `x11-calc-1Xc.h` (where 1Xc is 10c, 11c, 12c, 15c or 16c) to make the display wider.

```
#define DISPLAY_TOP        4 * SCALE_HEIGHT
#define DISPLAY_WIDTH      280 * SCALE_WIDTH
#define DISPLAY_HEIGHT     52 * SCALE_HEIGHT
```
Unfortunately the size of the fonts remains a bit of a problem.  Depending on the fonts available on the target system  you may be able to find a solution by modifying the font names in `x11-calc-fonts.c`.

Note - When recompiling after making any changes to the common code modules use `make clean; make voyager`.

Hope that helps!

**Comment by u2fly** [comment]
Just to be clear, I mostly talked about adding different UI coniguration for `320x200` and `320x240` (as the most common smallest resolution), instead of using scaling the original window.

> the only problem as VGA only supports 256 colours and the application currently requires 24-bit colour.

And for this, for custom UI setup for `320x200` and `320x240` should be used reduced palette as well.

**Comment by mike632t** [comment]
I see what you are getting at but unfortunately the user interface isn't 'skinned' so it isn't a possible to support a different resolution or colour depth by simply producing a new skin.  That is not to say the code could not be adapted to use various different skins instead of drawing each element separately, but I don't think it would be worth the (considerable) effort.

The original plan was to make every element of the display re-sizeable, allowing the user to make the window more or less what ever size they wanted (though not too small).  Unfortunately I've not yet figured out how to resize the text sensibly but I may get back to that at some point...
